NodeStructure/Models/ErrorViewModel.cs
namespace NodeStructure.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

NodeStructure/Models/NodesInfo.cs
using System.ComponentModel.DataAnnotations;

namespace NodeStructure.Models
{
    public class NodesInfo
    {
        [Key]
        public int nodeId { get; set; }
        public string nodeName { get; set; }
        public int parentNodeId { get; set; }
        public bool isActive { get; set; }
        public DateOnly startDate { get; set; }
    }
    public class NodesList
    {
        public int nodeId { get; set; }
        public string nodeName { get; set; }
        public List<SubNodesList> childnodes { get; set; }
    }
    public class SubNodesList
    {
        public int nodeId { get; set; }
        public string nodeName { get; set; }
    }
}

NodeStructure/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using NodeStructure.Models;
using System.Diagnostics;

namespace NodeStructure.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

NodeStructure/Controllers/NodesDetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NodeStructure.Models;

namespace NodeStructure.Controllers
{
    public class NodesDetailController : Controller
    {
        private readonly AppDbContext _context;

        public NodesDetailController(AppDbContext context)
        {
            _context = context;
        }

        // GET: NodesInfo
        public async Task<IActionResult> Index()
        {
            List<NodesList> nodesList = new List<NodesList>();
            NodesList Subnodes = new NodesList();
            var nodesparent = await _context.nodesInfo.Where(s => s.parentNodeId == 0).ToListAsync();
            foreach (var nodesMaster in nodesparent)
            {
                Subnodes = new NodesList();
                Subnodes.nodeId = nodesMaster.nodeId;
                Subnodes.nodeName = nodesMaster.nodeName;
                var nodeschild = await _context.nodesInfo.Where(s => s.parentNodeId == nodesMaster.nodeId).ToListAsync();
                List<SubNodesList> subNodesLists = new List<SubNodesList>();
                SubNodesList subList = new SubNodesList();
                foreach (var ChldNodes in nodeschild)
                {
                    subList = new SubNodesList();
                    subList.nodeId = ChldNodes.nodeId;
                    subList.nodeName = ChldNodes.nodeName;
                    subNodesLists.Add(subList);
                }
                Subnodes.childnodes = subNodesLists;
                nodesList.Add(Subnodes);
            }
            return View(nodesList);
        }

        
    }
}

NodeStructure/Controllers/NodesInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NodeStructure.Models;

namespace NodeStructure.Controllers
{
    public class NodesInfoController : Controller
    {
        private readonly AppDbContext _context;

        public NodesInfoController(AppDbContext context)
        {
            _context = context;
        }

        // GET: NodesInfo
        public async Task<IActionResult> Index()
        {
            return View(await _context.nodesInfo.ToListAsync());
        }

        // GET: NodesInfo/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nodesInfo = await _context.nodesInfo
                .FirstOrDefaultAsync(m => m.nodeId == id);
            if (nodesInfo == null)
            {
                return NotFound();
            }

            return View(nodesInfo);
        }

        // GET: NodesInfo/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: NodesInfo/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("nodeId,nodeName,parentNodeId,isActive,startDate")] NodesInfo nodesInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nodesInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nodesInfo);
        }

        // GET: NodesInfo/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nodesInfo = await _context.nodesInfo.FindAsync(id);
            if (nodesInfo == null)
            {
                return NotFound();
            }
            return View(nodesInfo);
        }

        // POST: NodesInfo/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("nodeId,nodeName,parentNodeId,isActive,startDate")] NodesInfo nodesInfo)
        {
            if (id != nodesInfo.nodeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nodesInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NodesInfoExists(nodesInfo.nodeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nodesInfo);
        }

        // GET: NodesInfo/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var nodesInfo = await _context.nodesInfo
                .FirstOrDefaultAsync(m => m.nodeId == id);
            if (nodesInfo == null)
            {
                return NotFound();
            }

            return View(nodesInfo);
        }

        // POST: NodesInfo/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var nodesInfo = await _context.nodesInfo.FindAsync(id);
            if (nodesInfo != null)
            {
                _context.nodesInfo.Remove(nodesInfo);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NodesInfoExists(int id)
        {
            return _context.nodesInfo.Any(e => e.nodeId == id);
        }
    }
}

NodeStructure/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

NodeStructure/Views/NodesDetail/Index.cshtml
@model IEnumerable<NodeStructure.Models.NodesList>

@{
    ViewData["Title"] = "Index";
}

<h1>Nodes Structure</h1>

<ul>
    @foreach (var node in Model)
    {
        <li>
            <span>@node.nodeName</span>
            <ul>
                @foreach (var subNode in node.childnodes)
                {
                    <li>@subNode.nodeName</li>
                }
            </ul>
        </li>
    }
</ul>

NodeStructure/Views/NodesInfo/Create.cshtml
@model NodeStructure.Models.NodesInfo

@{
    ViewData["Title"] = "Create";
}

<h4> Create Nodes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="nodeName" class="control-label"></label>
                <input asp-for="nodeName" class="form-control" />
                <span asp-validation-for="nodeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="parentNodeId" class="control-label"></label>
                <input asp-for="parentNodeId" class="form-control" />
                <span asp-validation-for="parentNodeId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isActive" /> @Html.DisplayNameFor(model => model.isActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="startDate" class="control-label"></label>
                <input asp-for="startDate" class="form-control" type="date" />
                <span asp-validation-for="startDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NodeStructure/Views/NodesInfo/Delete.cshtml
@model NodeStructure.Models.NodesInfo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Nodes</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nodeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nodeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nodeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nodeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.parentNodeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.parentNodeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.startDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.startDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="nodeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

NodeStructure/Views/NodesInfo/Details.cshtml
@model NodeStructure.Models.NodesInfo

@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>Nodes Detail</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.nodeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.nodeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.nodeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.nodeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.parentNodeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.parentNodeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isActive)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isActive)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.startDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.startDate)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.nodeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

NodeStructure/Views/NodesInfo/Edit.cshtml
@model NodeStructure.Models.NodesInfo

@{
    ViewData["Title"] = "Edit";
}

<h4>Edit Nodes</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="nodeId" />
            <div class="form-group">
                <label asp-for="nodeName" class="control-label"></label>
                <input asp-for="nodeName" class="form-control" />
                <span asp-validation-for="nodeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="parentNodeId" class="control-label"></label>
                <input asp-for="parentNodeId" class="form-control" />
                <span asp-validation-for="parentNodeId" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isActive" /> @Html.DisplayNameFor(model => model.isActive)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="startDate" class="control-label"></label>
                <input asp-for="startDate" class="form-control" type="date" />
                <span asp-validation-for="startDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

NodeStructure/Views/NodesInfo/Index.cshtml
@model IEnumerable<NodeStructure.Models.NodesInfo>

@{
    ViewData["Title"] = "Index";
}

<h1>Nodes Info</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.nodeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nodeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.parentNodeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isActive)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.startDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nodeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nodeName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.parentNodeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.isActive)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.startDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.nodeId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.nodeId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.nodeId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

NodeStructure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NodeStructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NodeStructure.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @* <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NodeStructure</a> *@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NodesInfo" asp-action="Index">Nodes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="NodesDetail" asp-action="Index">Nodes Structure</a>
                        </li>
@*                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - NodeStructure - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>